// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/careers": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/design-system": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/services" | "/careers" | "/contact" | "/design-system";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/services.tsx": {
    id: "routes/services";
    page: "/services";
  };
  "routes/careers.tsx": {
    id: "routes/careers";
    page: "/careers";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/design-system.tsx": {
    id: "routes/design-system";
    page: "/design-system";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/home": typeof import("./src/routes/home.tsx");
  "routes/about": typeof import("./src/routes/about.tsx");
  "routes/services": typeof import("./src/routes/services.tsx");
  "routes/careers": typeof import("./src/routes/careers.tsx");
  "routes/contact": typeof import("./src/routes/contact.tsx");
  "routes/design-system": typeof import("./src/routes/design-system.tsx");
};