// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:lang": {
    params: {
      "lang": string;
    };
  };
  "/:lang/about": {
    params: {
      "lang": string;
    };
  };
  "/:lang/careers": {
    params: {
      "lang": string;
    };
  };
  "/:lang/contact": {
    params: {
      "lang": string;
    };
  };
  "/:lang/services": {
    params: {
      "lang": string;
    };
  };
  "/:lang/privacy": {
    params: {
      "lang": string;
    };
  };
  "/admin/login": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/pages": {
    params: {};
  };
  "/admin/pages/:slug": {
    params: {
      "slug": string;
    };
  };
  "/admin/projects": {
    params: {};
  };
  "/admin/services": {
    params: {};
  };
  "/admin/team": {
    params: {};
  };
  "/admin/testimonials": {
    params: {};
  };
  "/admin/positions": {
    params: {};
  };
  "/admin/settings": {
    params: {};
  };
  "/admin/media": {
    params: {};
  };
  "/design-system": {
    params: {};
  };
  "/sandbox/home": {
    params: {};
  };
  "/sandbox/services": {
    params: {};
  };
  "/sandbox/team": {
    params: {};
  };
  "/sandbox/careers": {
    params: {};
  };
  "/sandbox/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/:lang" | "/:lang/about" | "/:lang/careers" | "/:lang/contact" | "/:lang/services" | "/:lang/privacy" | "/admin/login" | "/admin" | "/admin/pages" | "/admin/pages/:slug" | "/admin/projects" | "/admin/services" | "/admin/team" | "/admin/testimonials" | "/admin/positions" | "/admin/settings" | "/admin/media" | "/design-system" | "/sandbox/home" | "/sandbox/services" | "/sandbox/team" | "/sandbox/careers" | "/sandbox/contact";
  };
  "routes/root-redirect.tsx": {
    id: "routes/root-redirect";
    page: "/";
  };
  "routes/locale-layout.tsx": {
    id: "routes/locale-layout";
    page: "/:lang" | "/:lang/about" | "/:lang/careers" | "/:lang/contact" | "/:lang/services" | "/:lang/privacy";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/:lang";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/:lang/about";
  };
  "routes/careers.tsx": {
    id: "routes/careers";
    page: "/:lang/careers";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/:lang/contact";
  };
  "routes/services.tsx": {
    id: "routes/services";
    page: "/:lang/services";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/:lang/privacy";
  };
  "routes/admin.login.tsx": {
    id: "routes/admin.login";
    page: "/admin/login";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin" | "/admin/pages" | "/admin/pages/:slug" | "/admin/projects" | "/admin/services" | "/admin/team" | "/admin/testimonials" | "/admin/positions" | "/admin/settings" | "/admin/media";
  };
  "routes/admin.dashboard.tsx": {
    id: "routes/admin.dashboard";
    page: "/admin";
  };
  "routes/admin.pages.tsx": {
    id: "routes/admin.pages";
    page: "/admin/pages";
  };
  "routes/admin.pages.$slug.tsx": {
    id: "routes/admin.pages.$slug";
    page: "/admin/pages/:slug";
  };
  "routes/admin.projects.tsx": {
    id: "routes/admin.projects";
    page: "/admin/projects";
  };
  "routes/admin.services.tsx": {
    id: "routes/admin.services";
    page: "/admin/services";
  };
  "routes/admin.team.tsx": {
    id: "routes/admin.team";
    page: "/admin/team";
  };
  "routes/admin.testimonials.tsx": {
    id: "routes/admin.testimonials";
    page: "/admin/testimonials";
  };
  "routes/admin.positions.tsx": {
    id: "routes/admin.positions";
    page: "/admin/positions";
  };
  "routes/admin.settings.tsx": {
    id: "routes/admin.settings";
    page: "/admin/settings";
  };
  "routes/admin.media.tsx": {
    id: "routes/admin.media";
    page: "/admin/media";
  };
  "routes/design-system.tsx": {
    id: "routes/design-system";
    page: "/design-system";
  };
  "routes/sandbox.home.tsx": {
    id: "routes/sandbox.home";
    page: "/sandbox/home";
  };
  "routes/sandbox.services.tsx": {
    id: "routes/sandbox.services";
    page: "/sandbox/services";
  };
  "routes/sandbox.team.tsx": {
    id: "routes/sandbox.team";
    page: "/sandbox/team";
  };
  "routes/sandbox.careers.tsx": {
    id: "routes/sandbox.careers";
    page: "/sandbox/careers";
  };
  "routes/sandbox.contact.tsx": {
    id: "routes/sandbox.contact";
    page: "/sandbox/contact";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/root-redirect": typeof import("./src/routes/root-redirect.tsx");
  "routes/locale-layout": typeof import("./src/routes/locale-layout.tsx");
  "routes/home": typeof import("./src/routes/home.tsx");
  "routes/about": typeof import("./src/routes/about.tsx");
  "routes/careers": typeof import("./src/routes/careers.tsx");
  "routes/contact": typeof import("./src/routes/contact.tsx");
  "routes/services": typeof import("./src/routes/services.tsx");
  "routes/privacy": typeof import("./src/routes/privacy.tsx");
  "routes/admin.login": typeof import("./src/routes/admin.login.tsx");
  "routes/admin": typeof import("./src/routes/admin.tsx");
  "routes/admin.dashboard": typeof import("./src/routes/admin.dashboard.tsx");
  "routes/admin.pages": typeof import("./src/routes/admin.pages.tsx");
  "routes/admin.pages.$slug": typeof import("./src/routes/admin.pages.$slug.tsx");
  "routes/admin.projects": typeof import("./src/routes/admin.projects.tsx");
  "routes/admin.services": typeof import("./src/routes/admin.services.tsx");
  "routes/admin.team": typeof import("./src/routes/admin.team.tsx");
  "routes/admin.testimonials": typeof import("./src/routes/admin.testimonials.tsx");
  "routes/admin.positions": typeof import("./src/routes/admin.positions.tsx");
  "routes/admin.settings": typeof import("./src/routes/admin.settings.tsx");
  "routes/admin.media": typeof import("./src/routes/admin.media.tsx");
  "routes/design-system": typeof import("./src/routes/design-system.tsx");
  "routes/sandbox.home": typeof import("./src/routes/sandbox.home.tsx");
  "routes/sandbox.services": typeof import("./src/routes/sandbox.services.tsx");
  "routes/sandbox.team": typeof import("./src/routes/sandbox.team.tsx");
  "routes/sandbox.careers": typeof import("./src/routes/sandbox.careers.tsx");
  "routes/sandbox.contact": typeof import("./src/routes/sandbox.contact.tsx");
};