// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/careers": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/design-system": {
    params: {};
  };
  "/services/diagnose": {
    params: {};
  };
  "/services/coach": {
    params: {};
  };
  "/services/create": {
    params: {};
  };
  "/services/optimize": {
    params: {};
  };
  "/services/build": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/careers" | "/contact" | "/design-system" | "/services/diagnose" | "/services/coach" | "/services/create" | "/services/optimize" | "/services/build";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/careers.tsx": {
    id: "routes/careers";
    page: "/careers";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/design-system.tsx": {
    id: "routes/design-system";
    page: "/design-system";
  };
  "routes/services/diagnose.tsx": {
    id: "routes/services/diagnose";
    page: "/services/diagnose";
  };
  "routes/services/coach.tsx": {
    id: "routes/services/coach";
    page: "/services/coach";
  };
  "routes/services/create.tsx": {
    id: "routes/services/create";
    page: "/services/create";
  };
  "routes/services/optimize.tsx": {
    id: "routes/services/optimize";
    page: "/services/optimize";
  };
  "routes/services/build.tsx": {
    id: "routes/services/build";
    page: "/services/build";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/home": typeof import("./src/routes/home.tsx");
  "routes/about": typeof import("./src/routes/about.tsx");
  "routes/careers": typeof import("./src/routes/careers.tsx");
  "routes/contact": typeof import("./src/routes/contact.tsx");
  "routes/design-system": typeof import("./src/routes/design-system.tsx");
  "routes/services/diagnose": typeof import("./src/routes/services/diagnose.tsx");
  "routes/services/coach": typeof import("./src/routes/services/coach.tsx");
  "routes/services/create": typeof import("./src/routes/services/create.tsx");
  "routes/services/optimize": typeof import("./src/routes/services/optimize.tsx");
  "routes/services/build": typeof import("./src/routes/services/build.tsx");
};